export const projects = [
	{
		slug: 'haus-inmobiliary',
		title: 'Haus Inmobiliary',
		website: 'https://haus-inmobiliary.netlify.app',
		github: 'https://github.com/lucianoadamczuk/haus-inmobiliary',
		technologies: ['ux-ui', 'tailwind', 'swiper-js', 'typescript'],
		src: '/assets/images/projects/haus-inmobiliary.jpg',
	},
	{
		slug: 'church-i18n',
		title: 'Church I18N',
		website: 'https://church-i18n.netlify.app',
		github: 'https://github.com/lucianoadamczuk/church-i18n',
		technologies: ['css', 'swiper-js', 'i18n'],
		src: '/assets/images/projects/church-i18n.jpg',
	},
	{
		slug: 'gamesphere',
		title: 'GameSphere',
		website: 'https://adamczuk-gamesphere.netlify.app/',
		github: 'https://github.com/lucianoadamczuk/game-sphere',
		technologies: ['next-js', 'next-ui', 'tailwind', 'typescript', 'swiper-js'],
		src: '/assets/images/projects/game-sphere.jpg',
	},
	{
		slug: 'bibiana-garcia',
		title: 'Bibiana Garcia',
		website: 'https://bibiana-garcia.netlify.app',
		github: 'https://github.com/lucianoadamczuk/bibiana-garcia',
		technologies: ['react', 'photoshop', 'framer-motion', 'ux-ui'],
		src: '/assets/images/projects/bibiana-garcia.jpg',
	},
	{
		slug: 'genaro-pedrazzoli',
		title: 'Genaro Pedrazzoli',
		website: 'https://genaro-pedrazzoli.netlify.app/',
		github: 'https://github.com/lucianoadamczuk/genaro-pedrazzoli-updated',
		technologies: ['next-js', 'css', 'photoshop', 'typescript', 'context'],
		src: '/assets/images/projects/genaro-pedrazzoli.jpg',
	},
	{
		slug: 'netflix-replica',
		title: 'Netflix Replica',
		website: 'https://net-fli-x-adamczuk.netlify.app/',
		github: 'https://github.com/lucianoadamczuk/netflix-replica',
		technologies: [
			'context',
			'react',
			'react-router-dom',
			'fetch',
			'css-modules',
			'swiper-js',
			'typescript',
		],
		src: '/assets/images/projects/netflix-replica.jpg',
	},
	{
		slug: 'go-to-egypt',
		title: 'Go To Egypt',
		website: 'https://adamczuk-gotoegypt.netlify.app',
		github: 'https://github.com/lucianoadamczuk/egypt',
		technologies: [
			'react',
			'tailwind',
			'react-router-dom',
			'photoshop',
			'framer-motion',
			'swiper',
		],
		src: '/assets/images/projects/go-to-egypt.jpg',
	},
	{
		slug: 'duolingo-replica',
		title: 'Duolingo Replica',
		website: 'https://lucianoadamczuk.github.io/duolingo-replica/',
		github: 'https://github.com/lucianoadamczuk/duolingo-replica',
		technologies: ['react', 'bootstrap', 'photoshop'],
		src: '/assets/images/projects/duolingo-replica.jpg',
	},
	{
		slug: 'ecommerce-coderhouse',
		title: 'Ecommerce Coderhouse',
		website: 'https://ecommerce-gigamesh.netlify.app',
		github: 'https://github.com/lucianoadamczuk/eCommerce',
		technologies: ['react', 'tailwind', 'framer-motion'],
		src: '/assets/images/projects/eCommerce-coderhouse.jpg',
	},
];
